import Head from 'next/head'
import Layout from './layout'
import Experience from '../components/Experience'
import Hero from '../components/Hero'
import About from '../components/About'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import { useCallback } from 'react'
import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";
import { particleOptions } from '../utils/Particle'


export default function Home({darkMode}) {

  const particlesInit = useCallback(async engine => {
    console.log(engine);
    // you can initiate the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
}, []);

const particlesLoaded = useCallback(async container => {
  await console.log(container);
}, []);
  return (
    <div className="dark">
      <Head>
        <title>Vishnu Surendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Particles className='z-0' id="tsparticles" init={particlesInit} loaded={particlesLoaded}  options= {particleOptions} />
        <div className='lg:mx-auto lg:max-w-6xl relative'>
          {/* Hero Section */}
          <Hero/>
          {/* About Section */}
          <About/>
          {/* Experience Section */}
          <Experience/>
          {/* Projects */}
          <Projects/>
          {/* Get in touch */}
          <Contact/>
        </div>
      </Layout>
    </div>
  )
}
