import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { MdDarkMode, MdLightMode } from 'react-icons/md'
import {GiHamburgerMenu} from 'react-icons/gi'
import { AiOutlineClose } from 'react-icons/ai'
import { useState } from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(true)
  const [hamMenu, setHamMenu] = useState(true);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Vishnu Surendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='py-10 px-10 min-h-screen dark:bg-neutral-900 bg'>
          <div className=' flex justify-between px-5'>
            <h1 className='text-4xl cursor-pointer dark:text-slate-200'>Vishnu</h1>
            <div className='dark:text-slate-200 flex justify-center items-center lg:hidden cursor-pointer text-2xl' 
              onClick={() => setHamMenu(!hamMenu)}> 
              {hamMenu ? <GiHamburgerMenu/> : <AiOutlineClose/>}
            </div>
            <ul className='items-center dark:text-slate-200 hidden lg:flex'>
              <li className='px-10 cursor-pointer hover:text-teal-500 transition ease-in'>Home</li>
              <li className='px-10 cursor-pointer hover:text-teal-500 transition ease-in'>Blog</li>
              <li className='px-10 cursor-pointer hover:text-teal-500 transition ease-in'>Skills</li>
              <li className='px-10 cursor-pointer hover:text-teal-500 transition ease-in'>Contact</li>
              <li className=' cursor-pointer text-2xl' onClick={() => setDarkMode(!darkMode)}>
                <div className='p-2 hover:bg-neutral-700 hover:text-slate-200 dark:hover:bg-slate-200 dark:hover:text-gray-900 transition ease-in rounded-xl'>
                  { darkMode ? <MdDarkMode/> : <MdLightMode/>}
                </div>
                </li>
            </ul>
          </div>
        </section>
      </main>
    </div>
  )
}
