import Head from 'next/head'
import { MdLocationOn } from 'react-icons/md'
import { AiOutlinePlus, AiOutlineMinus } from 'react-icons/ai'
import { BiChevronsDown } from 'react-icons/bi'
import {HiOutlineArrowNarrowRight} from 'react-icons/hi'
import { useRef, useState } from 'react'
import Router from 'next/router'
import Image from 'next/image';
import InstagramClone from '../public/Instagram-Clone.png';
import Layout from './layout'
import { AnimatePresence, motion } from 'framer-motion'
import { useTypewriter, Cursor } from 'react-simple-typewriter'
import { slideDown, slideFromLeft, fadeIn, fadeUp, slideFromRight } from '../utils/Animations'


export default function Home({darkMode}) {
  const [experienceOpen, setExperienceOpen] = useState(false)
  // const [darkMode, setDarkMode] = useState(true)
  const name = "Vishnu Surendran";
  const [text] = useTypewriter({
    words: ["<I am Vishnu Surendran/>", "<Front-end Web Developer/>", "<Electronics Enthusiast/>"],
    loop: 0,
  })

  const sendMail = () => {
    window.location.href = "mailto:vishnuksvichu12345@gmail.com"
  }
  return (
    <div className="dark">
      <Head>
        <title>Vishnu Surendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
          <div className='lg:mx-auto lg:max-w-5xl'>
            <motion.section className='py-5 flex flex-col px-5 justify-center min-h-screen' initial={'initial'} animate={'animate'} transition={{staggerChildren: 0.2}}>
              <div className='flex flex-col justify-center h-[80vh]'>
                <div className='mt-10 mb-8 dark:text-slate-200 leading-9'>
                  {/* <h1 className='text-5xl font-medium pb-2'><span className='text-hover'>H</span><span className='text-hover'>i</span><span className='text-hover'>,</span></h1> */}
                  <motion.h6 variants={slideFromLeft} className='text-teal-500 mb-4 text-sm md:text-base font-roboto_mono'>Hey there, <span className='text-xl md:text-2xl hand-wave'>\uD83D\uDC4B\uD83C\uDFFB</span></motion.h6>
                  <motion.div variants={fadeIn} className='overflow-hidden'>
                    <h3 className='text-3xl md:text-4xl lg:text-5xl font-medium tracking-tight font-roboto-mono mb-3'>
                      <span>{text}</span>
                      <Cursor cursorColor='#14B8A6'/>
                    </h3>
                  </motion.div>
                  <motion.h4 variants={fadeIn} className='text-lg md:text-xl lg:text-xl '> <span className='text-teal-500'>Software Engineer</span> @ <a href="https://www.qburst.com" target="_blank" rel="noreferrer"><span className='text-red-700'>Q</span>Burst</a></motion.h4>
                  {/* <p className=' text-teal-500 mb-3 text-sm md:text-base'>Front-end Developer | Electronics Enthusiast</p> */}
                  <motion.p variants={fadeIn} className=' leading-6 md:leading-7 lg:leading-8 text-slate-400 text-sm md:text-base'>I am a front-end software engineer with more than 1 year of experience in creating 
                    user-friendly and visually appealing web interfaces using technologies such as HTML, CSS, JavaScript 
                    and frameworks such as Angular, React JS, and Next.JS.</motion.p>
                </div>
                <motion.div variants={fadeIn} className='flex items-center justify-start '>
                  <button className='px-8 py-3 text-slate-200 hover:bg-teal-600 border-2 border-teal-400 rounded-3xl transition ease-in text-sm md:text-base'
                  onClick={() => Router.push('/about')}>
                    Get My Resume
                  </button>
                </motion.div>
              </div>
              <div className=' text-slate-200 flex justify-center items-center w-full h-[20vh]'>
                <motion.div variants={fadeUp} className='flex flex-col items-center'>
                  <span className='text-xs scroll-bounce '>Scroll Down</span>
                  <span><BiChevronsDown/></span>
                </motion.div>
              </div>
            </motion.section>
            {/* About Section */}
            <section className='flex flex-col py-10 px-5'>
              <motion.div className='flex flex-col justify-start leading-6 md:leading-7 lg:leading-8 text-sm md:text-base' initial={'initial'} whileInView={'animate'}        viewport={{once: true, amount: 1}} transition={{staggerChildren: 0.2}}>
                <motion.h2 variants={slideFromLeft} className=' dark:text-slate-200 text-2xl mb-10' id='skills'>About Me</motion.h2>
                <motion.p variants={slideFromRight} className='dark:text-slate-400 '>Hello! My name is Vishnu and I&apos;m passionate about creating visually stunning and user-friendly web interfaces.
                  I have a strong background in front-end technologies such as HTML, CSS, JavaScript, and experience with popular front-end frameworks and libraries
                  such as React, Angular. I am skilled in creating responsive, mobile-friendly websites.
                  I have experience in multiple project and industries, from simple landing pages to complex web applications. 
                  I am always up for new challenges and love to stay updated with new technologies and trends in the industry.
                  Currently I&apos;m working as Software Engineer at QBurst Technologies.
                </motion.p>
                <motion.p variants={slideFromRight} className='dark:text-slate-400 py-4' id='skills'>
                  Here are few technologies I&apos;ve been working with recently:
                </motion.p>
                <motion.div className='flex justify-start dark:text-slate-400 leading-9 px-5'>
                  <motion.ul className='pr-10 list-circle'>
                    <motion.li variants={slideFromRight} className='text-teal-500'> <span className='text-slate-400'>JavaScript</span></motion.li>
                    <motion.li variants={slideFromRight} className='text-teal-500'><span className='text-slate-400'>Angular</span></motion.li>
                    <motion.li variants={slideFromRight} className='text-teal-500'> <span className='text-slate-400'>TypeScript</span></motion.li>
                  </motion.ul>
                  <motion.ul className='list-circle'>
                    <motion.li variants={slideFromRight} className='text-teal-500'> <span className='text-slate-400'>Next.js</span></motion.li>
                    <motion.li variants={slideFromRight} className='text-teal-500'><span className='text-slate-400'>Tailwind</span></motion.li>
                    <motion.li variants={slideFromRight} className='text-teal-500'><span className='text-slate-400'>ReactJS</span></motion.li>
                  </motion.ul>
                </motion.div>
              </motion.div>
            </section>
            {/* Experience Section */}
            <section className='flex flex-col py-10 px-5'>
              <motion.div className='flex flex-col justify-start' initial={'initial'} whileInView={'animate'} viewport={{once: true, amount: 1}} transition={{staggerChildren: 0.2}}>
                <motion.h2 variants={slideFromLeft} className='dark:text-slate-200 text-2xl mb-10'>Where I&apos;ve Worked</motion.h2>
                <motion.div variants={fadeIn} className='flex justify-between items-center'>
                  <div>
                    <h4 className=' dark:text-slate-200 text-base md:text-lg'>Software Engineer @ <a href="https://www.qburst.com"><span className=' text-red-600'>Q</span>Burst</a></h4>
                    <p className='text-slate-400 italic text-xs md:text-sm pt-2 mb-3'>August 2021 - Present</p>
                  </div>
                  <div className=' dark:text-slate-200' onClick={() => setExperienceOpen(!experienceOpen)}>
                    {experienceOpen ? <AiOutlineMinus/>  : <AiOutlinePlus/>}
                  </div>
                </motion.div>
                <AnimatePresence>
                  {experienceOpen && 
                    <div className='overflow-hidden'>
                      <motion.div className='rounded-xl p-2 dark:bg-slate-800 bg-[#E5E7E9] flex flex-col' initial={'initial'} animate={'animate'} variants={slideDown} exit={slideDown.exit}>
                        <div className='flex items-center dark: text-slate-400 my-2'>
                          <span className='px-2 text-teal-500'><MdLocationOn/></span>
                          <p className=' text-xs'>Kochi, Kerala</p>
                        </div>
                        <div className='flex px-2 dark:text-slate-400 leading-6 md:leading-7 lg:leading-8 text-sm md:text-base'>
                          <p>Developing front-end application solutions using Angular framework</p>
                        </div>
                        <div className='flex justify-center py-3 leading-6 md:leading-7 lg:leading-8 text-xs md:text-sm'>
                          <ul className='flex items-center justify-around w-full'>
                            <li className='px-4 py-1 rounded-3xl dark:bg-neutral-900 bg-[#2A3A45] text-teal-400'>JavaScript</li>
                            <li className='px-4 py-1 rounded-3xl dark:bg-neutral-900 bg-[#2A3A45] text-teal-400'>Angular</li>
                            <li className='px-4 py-1 rounded-3xl dark:bg-neutral-900 bg-[#2A3A45] text-teal-400'>HTML</li>
                            <li className='px-4 py-1 rounded-3xl dark:bg-neutral-900 bg-[#2A3A45] text-teal-400'>CSS</li>
                          </ul>
                        </div>
                      </motion.div>
                    </div>
                  }
                  </AnimatePresence>
              </motion.div>
            </section>
            {/* Projects */}
            <motion.section className='flex flex-col py-10 px-5' initial={'initial'} whileInView={'animate'} viewport={{once: true, amount: 1}} transition={{staggerChildren: 0.2}}>
              <div className='flex'>
                <motion.h2 variants={slideFromLeft} className=' dark:text-slate-200 text-2xl mb-10' id='projects'>Things I&apos;ve Built</motion.h2>
              </div>
              <motion.div variants={fadeUp} className='flex flex-wrap py-3 px-5 sm:px-0'>
                <div className='rounded-xl project-tile flex flex-col items-center dark:text-slate-200 w-full overflow-hidden dark:bg-slate-800 sm:w-1/2 md:w-1/3'>
                  <div className=' overflow-hidden'>
                  <Image src={InstagramClone} alt="instagramClone" width={600}  height={600}  className='project-img'/>
                  </div>
                  <div className='flex flex-col w-full justify-start py-4 px-10'>
                    <h4 className='py-1 leading-6 md:leading-7 lg:leading-8 text-base md:text-lg'>Instagram Clone Web App</h4>
                    <p className='subtext text-slate-400 text-xs md:text-sm'>Web Development</p>
                    <p className='subtext-open text-teal-400 text-xs md:text-sm flex items-center cursor-pointer font-medium'>
                      <span className='mr-2'>View project</span>
                      <HiOutlineArrowNarrowRight/>
                    </p>
                  </div>
                </div>
              </motion.div>
            </motion.section>
            {/* Get in touch */}
            <section className='flex flex-col px-5 py-10 mb-10 box'>
              <motion.div className='flex flex-col justify-center' initial={'initial'} whileInView={'animate'} viewport={{once: true, amount: 1}} transition={{staggerChildren: 0.2}}>
                <motion.h2 variants={slideFromLeft} className='dark:text-slate-200 text-2xl mb-10' id='contact'>Get In Touch</motion.h2>
                <motion.p variants={slideFromRight} className=' text-slate-400 mb-5 leading-6 md:leading-7 lg:leading-8 text-sm md:text-base'>Thank you for visiting my portfolio website. Although I’m not currently looking for any new opportunities, my inbox is always open. 
                  Whether you have a question or just want to say hi, I’ll try my best to get back to you!. Alternatively, you can also find me on LinkedIn. 
                  Feel free to connect with me and view my professional profile for more information about my background and experience.
                </motion.p>
                <motion.div variants={fadeIn} className='flex items-center justify-start'>
                  <button className='px-8 py-3 dark:text-slate-200 hover:bg-teal-500 border-2 border-teal-500 rounded-3xl transition ease-in' onClick={() => sendMail()}>Contact Me</button>
                </motion.div>
              </motion.div>
            </section>
          </div>
        </Layout>
      </div>
    </div>
  )
}
